# ============================================================
#  JUJUTSU KAISEN SERVICE – Configuración
#  Archivo: src/main/resources/application.properties
# ============================================================

# Puerto (Render asigna la variable PORT automáticamente)
server.port=${PORT:8080}

# ── Conexión a Supabase (Session Pooler – compatible IPv4) ──
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?user=postgres.cazxvbycmisoljeuonct&password=animepaswword&sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Nombre de la aplicación
spring.application.name=jjk-service