# ============================================================
#  JUJUTSU KAISEN SERVICE – Configuración producción
# ============================================================

server.port=${PORT:8080}

# ── Conexión directa a Supabase ───────────────────────────
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?user=postgres.cazxvbycmisoljeuonct&password=animepaswword&sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=2

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.application.name=jjk-service